server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/*/users/**, /user-service/v3/api-docs

        - id: product_service
          uri: http://localhost:8083
          predicates:
            - Path=/api/*/products/**, /product-service/v3/api-docs

        - id: notification_service
          uri: http://localhost:8084
          predicates:
            - Path=/api/*/notifications/**, /notification-service/v3/api-docs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /user-service/v3/api-docs
        name: User Service
      - url: /product-service/v3/api-docs
        name: Product Service
      - url: /notification-service/v3/api-docs
        name: Notification Service

logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            handler:
              RoutePredicateHandlerMapping: TRACE