server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/*/users/**

        - id: product_service
          uri: http://localhost:8083
          predicates:
            - Path=/api/*/products/**

        - id: notification_service
          uri: http://localhost:8084
          predicates:
            - Path=/api/*/notifications/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            handler:
              RoutePredicateHandlerMapping: TRACE